dbt-labs/dbt-athena

.github/workflows/python-publish.yml, CHANGELOG.md, dbt/adapters/athena/impl.py, setup.py
Ported from https://github.com/Tomme/dbt-athena/pull/82 with some tweaks.
=> [BUGFIX] Fix glue partition handling

dbt/adapters/athena/impl.py, dbt/include/athena/macros/adapters/metadata.sql
_We've been running an internal fork of dbt-athena for little while, so I'm bringing over a few PRs we've made to this new awesome community release 😄_ 
---
This PR fixes the issue where setting the owner in schema.yml did not propagate to generated dbt docs.
The issue was cause by having null as table_owner, in metadata.sql file.
Because the table owner is not populated in Athena catalog, the simplest fix was to parse the manifest after the catalog is retrieved and manually append the owner to each model. Because the athena__get_catalog macro in metadata.sql always returned null for table_owner I completely removed that column and it gets appended when adding the owner from manifest instead.
**Results**
When you define:
```yml
models:
- name: batch_decision_checks
config:
tags:
- …
```
=> Get model owner from manifest

dbt/adapters/athena/connections.py
Copy/paste from: https://github.com/Tomme/dbt-athena/pull/117
Closes #17
=> Use correct escaper for `INSERT` queries

dbt/adapters/athena/connections.py, dbt/adapters/athena/impl.py, dbt/adapters/athena/session.py
Porting the work made in https://github.com/Tomme/dbt-athena/pull/56 https://github.com/Tomme/dbt-athena/pull/121 https://github.com/Tomme/dbt-athena/pull/124 https://github.com/Tomme/dbt-athena/pull/125. Going with approach https://github.com/Tomme/dbt-athena/pull/125 since it prevents from asking multiple times MFA serial.
=> fix: share same boto session between every calls

.github/workflows/python-publish.yml, CHANGELOG.md, dbt/adapters/athena/connections.py, dbt/adapters/athena/impl.py, dbt/adapters/athena/query_headers.py, dbt/adapters/athena/relation.py, dbt/adapters/athena/session.py, dbt/include/athena/macros/adapters/metadata.sql, dbt/include/athena/macros/materializations/models/incremental/helpers.sql, setup.py
* https://github.com/dbt-athena/dbt-athena/pull/6
* https://github.com/dbt-athena/dbt-athena/pull/9
* https://github.com/dbt-athena/dbt-athena/pull/10
* https://github.com/dbt-athena/dbt-athena/pull/18
* https://github.com/dbt-athena/dbt-athena/pull/16
=> Release 1.0.4

dbt/include/athena/macros/materializations/models/helpers_iceberg.sql
When running this model:
```
{{ config(
materialized='table',
format='iceberg',
schema='silver'
) }}
SELECT
'abc' AS test_string
, true AS test_bool
, 123 AS test_int
, 123.45 AS test_float
, CAST(1234.567 AS DECIMAL(7, 3)) AS test_decimal
, CAST(34 AS BIGINT) AS test_bigint
, CAST(123.33 AS DOUBLE) AS test_double
, ARRAY['a'] AS test_array_string
, ARRAY[1] AS test_array_int
, ARRAY[false] AS test_array_bool
, MAP(ARRAY['a'], ARRAY[1]) AS test_map_string_int
, MAP(ARRAY['a'], ARRAY['b']) AS test_map_string_string
, MAP(ARRAY['a'], ARRAY[true]) AS test_map_string_bool
, MAP(ARRAY[1], ARRAY['a']) AS test_map_int_string
, MAP(ARRAY[1], ARRAY[1]) AS test_map_int_int
, MAP(ARRAY[true], ARRAY['a']) AS test_map_bool_string
, MAP(ARRAY[ARRAY['a']], ARRAY['a']) AS test_map_arrstring_string
, …
```
=> Fix edge case on Iceberg types

dbt/adapters/athena/impl.py, dbt/include/athena/macros/materializations/models/incremental/incremental.sql
Fixes #42 
This was caused by a refactor of the incremental materialization in dbt core 1.3: https://github.com/dbt-labs/dbt-core/pull/5359/files
* ✅ I added an implementation of the supported incremental strategies (see PR above that introduced it in dbt 1.3)
* ✅ I use a default in a slightly different way, but same as how snowflake and bigquery adapter do it: 
* https://github.com/dbt-labs/dbt-snowflake/blob/22a0ac6701da6d7b9c4f009e23c0a58a9fdc7641/dbt/include/snowflake/macros/materializations/incremental.sql#L32
* https://github.com/dbt-labs/dbt-bigquery/pull/223/files#diff-167e3557df7f18f1520c5db0045dfac9923e38a617c909d703be844192b28ebeR17
In the long term we should probably refactor the `incremental.sql` and provide strategies macro's for each of them (with a 'default'). See here: …
=> Fix default incremental strategy

dbt/adapters/athena/session.py
I run a dbt project usually with `threads: 4` or `threads: 8`. When I switched my projects away from the `Tomme/dbt-athena` to this adapter, I received:
```
18:29:33.190966 [info ] [MainThread]: Found 79 models, 9 tests, 0 snapshots, 0 analyses, 510 macros, 0 operations, 0 seed files, 64 sources, 0 exposures, 0 metrics
18:29:33.193761 [info ] [MainThread]: 
18:29:33.194168 [debug] [MainThread]: Acquiring new athena connection "master"
18:29:33.197412 [debug] [ThreadPool]: Acquiring new athena connection "list_awsdatacatalog"
18:29:33.198456 [debug] [ThreadPool]: Acquiring new athena connection "list_awsdatacatalog"
18:29:33.198652 [debug] [ThreadPool]: Acquiring new athena connection "list_awsdatacatalog"
18:29:33.198835 [debug] [ThreadPool]: Acquiring new athena connection …
```
=> fix: multi-thread issues by removing global boto3 session

README.md, dbt/adapters/athena/connections.py, dbt/include/athena/macros/materializations/models/helpers_iceberg.sql, dbt/include/athena/macros/materializations/models/incremental/helpers.sql, dbt/include/athena/macros/materializations/models/incremental/incremental.sql, dbt/include/athena/macros/materializations/models/incremental/merge.sql, dbt/include/athena/macros/materializations/models/table/table.sql
Now Iceberg tables support incremental models with `append` (for both v2 and v3) and `merge` (v3 only).
I added the specifications in the README.md.
I am also agree with a comment made in an other PR about splitting the incremental sql file according to dbt-core standard. Should we do this in this PR or in an other one ?
=> feat: add incremental append and merge for iceberg tables

README.md, dbt/include/athena/macros/materializations/models/incremental/incremental.sql
I was testing dbt-athena@v1.3.2 today and I ran into an issue when my incremental table runs. 
This is a basic incremental materialization, with the default strategy `insert_overwrite` is used.
```
{{
config(materialized='incremental', incremental_strategy='insert_overwrite')
}}
```
The first time (full refresh) it loads fine. After that, when incremental mode kicks in, I get an error:
```
21:17:53.743463 [debug] [Thread-1 (]: Opening a new connection, currently in state closed
Failed to execute query.
Traceback (most recent call last):
File "/Users/jesse.dobbelaere/XXX/.venv/lib/python3.10/site-packages/pyathena/common.py", line 494, in _execute
query_id = retry_api_call(
File "/Users/jesse.dobbelaere/XXX/.venv/lib/python3.10/site-packages/pyathena/util.py", line 68, in retry_api_call …
```
=> fix: incremental table with insert_overwrite

README.md, dbt/include/athena/macros/materializations/models/incremental/column_helpers.sql, dbt/include/athena/macros/materializations/models/incremental/incremental.sql, dbt/include/athena/macros/materializations/models/incremental/merge.sql, dbt/include/athena/macros/materializations/models/incremental/on_schema_change.sql
This PR introduces on_schema_change feature to the iceberg tables (append was already handled, we needed it for the merge strategy).
Fixes #51
I used this model (I tested all the on_schema_change methods, I spent more time on the `sync_all_columns`):
```sql
{{ config(
incremental_strategy='merge',
unique_key='test_timestamp',
partitioned_by=['hour(test_timestamp)'],
on_schema_change='sync_all_columns',
format='iceberg',
) }}
SELECT
CAST(ts AS timestamp) AS test_timestamp
, CAST(ts AS DATE) AS test_date
, 'abc' AS test_string
, 'cde' AS test_useless_string
, true AS test_bool
, 123 AS test_int
, 123.45 AS test_float
, CAST(1234.567 AS DECIMAL(7, 3)) AS test_decimal
, CAST(34 AS BIGINT) AS test_bigint
, CAST(123.33 AS DOUBLE) AS test_double
, ARRAY['a'] AS …
```
=> feat: add on_schema_change for iceberg tables

dbt/adapters/athena/impl.py, tests/unit/test_adapter.py
There's a bug that would delete a table together with all tables that share the same s3 `external_location` as prefix.
Example:
- table_a lives at s3://mybucket/foo
- table_b lives at s3://mybucket/foo_bar
dbt-athena will delete everything under s3://mybucket/foo, which includes data for table_b (unintentionally, table would be empty afterwards)
The fix is to append a trailing slash '/' to the s3 path, so that only the right data gets deleted (in above example everything under `s3://mybucket/foo/`, which now does **not** include `s3://mybucket/foo_bar`
=> Fix deletion of tables with same prefix location

dbt/adapters/athena/impl.py, dbt/include/athena/macros/materializations/models/table/create_table_as.sql, tests/unit/test_adapter.py
I took a first stab at https://github.com/dbt-athena/dbt-athena/issues/58 as a follow-up on the discussion on [slack](https://getdbt.slack.com/archives/C013MLFR7BQ/p1669050058685359):
This is resolving the endless loop of `HIVE_PATH_ALREADY_EXISTS` errors, that occur whenever dbt receives a 503 Slow Down Error from s3, during a CTA statement after it has already written partial files to s3. For typical table materializations with static s3 locations, i.e. when using `external_location` or `s3_data_naming in ['table_table', 'schema_table']`, retrying keeps failing as the table was already dropped from Glue, while the partially written files never get deleted. This is 
- adding a new `prune_s3_table_location()` method to the AthenaAdapter
- adding a new method that handles s3 deletions, …
=> fix: prune static s3 locations before CTA

dbt/include/athena/macros/adapters/relation.sql
This fix https://github.com/dbt-athena/dbt-athena/issues/98
When working with incremental and append model in parquet, my path was not pruned....looking at the code the drop is excluding append mode.
We should drop the s3 path as well when working with append mode as tables are accumulated, used for inserts and drop at the end.
<pre>
{{ config(
incremental_strategy='append',
format='parquet',
s3_data_naming='table'
) }}
select
user_id,
status,
user_name
from {{ ref('parquet_example_1') }}
</pre>
=> fix: path should be dropped for append

dbt/adapters/athena/impl.py
Fix #101 using `posixpath` instead of `path`
=> fix: backslash in windows os

.github/dependabot.yml
Add dependabot to automatically bump dependencies.
If a specific library is broken, we can close the PR and dependabot won't open any pr for that specific version.
=> chore: add weekly dependabot

dbt/adapters/athena/impl.py, dbt/include/athena/macros/adapters/relation.sql, tests/unit/test_adapter.py, tests/unit/utils.py
This should aim to close https://github.com/dbt-athena/dbt-athena/issues/94
Add a new method to the adapter that consider the table type for the drop, doing so it allows to have a drop statement that is indipendnt from the config.
* parquet models
* table
* incremental
* iceberg with merge and full statement
=> chore: improve the drop_relation default macro

dbt/include/athena/macros/materializations/seeds/helpers.sql
Currently, we cannot set an `external_location` config for individual seed models. This PR is adding support to set an `external_location` when seeding seeds.
=> feat: add support for external_location for seeds

dbt/adapters/athena/impl.py, dbt/include/athena/macros/adapters/relation.sql
This PR fixes two issues with the updated `drop_table` macro in case the table doesn't exist:
- Logging the `EntityNotFoundException` directly leads to an error `Object of type EntityNotFoundException is not JSON serializable` when using JSON logging
- When the table is missing in Glue and `rel_type` is `None`, the drop table statement becomes `DROP None IF EXISTS <table>`
=> fix: prevent errors in drop_table macro when table doesn'tt exist

dbt/adapters/athena/impl.py
This should fix the issue raised on https://github.com/dbt-athena/dbt-athena/issues/113
When a model was originally a view, and then switched to a table `table["Table"]["StorageDescriptor"]["Location"]` is empty. Therefore we try pass an empty string downstream, that lead to a "invalid bucket"  
I was not able to fully reproduced what was raised in the ticket, but anyhow this PR add a safeguard, where _delete_from_s3 is called when location is not empty
=> fix: improve clean-up table

.github/workflows/ci.yml, Makefile, README.md, dbt/adapters/athena/__version__.py, dbt/adapters/athena/connections.py, dbt/adapters/athena/impl.py, dbt/adapters/athena/relation.py, dev-requirements.txt, requirements.txt, setup.py, tests/conftest.py, tests/unit/test_adapter.py
This PR should cover this https://github.com/dbt-athena/dbt-athena/issues/136 also include python 3.11 to the matrix, doing so we know that we support the adapter with python 3.11
I tested with multiple models:
* parquet table
* parquet incremental and with partitions
* iceberg table
* iceberg append
* iceberg merge
=> chore: upgrade to dbt core v1.4.0

dbt/adapters/athena/impl.py, dbt/include/athena/macros/materializations/models/table/create_table_as.sql, tests/unit/constants.py, tests/unit/test_adapter.py
This PR aim to create separate clients for each AWS SDK call, doing so we avoid to leave open connections.
It also introduce get_table_location  and make `delete_from_s3` method available (to use in some custom macros=
=> chore: refactor boto3 calls and expose more functions

dbt/adapters/athena/impl.py, tests/unit/test_adapter.py, tests/unit/utils.py
* Avoid to pass boto3 client around, but re-create a new client for each function call. Doing so we properly close connections, and we can easily have functions exposable to the adapter as macro.
* Fix an edge case where in case of views the table location is empty
=> chore: get boto3 client in function and cover some edge cases

dbt/adapters/athena/impl.py, dbt/include/athena/macros/materializations/snapshots/snapshot.sql
The snapshot logic does not utilize the cache that is built as database=None is different from database='awsdatacatalog'. 
This shows up with the following message in the log output
```
On "snapshot.dbt_dev.model_snapshot_1": cache miss for schema ".analytics_dev", this is inefficient
```
It also fixes a run time error that is due to dbt incorrectly labeling that the target snapshot doesn't exist even when the table is present
Athena allows database to be optional and treats all requests with a default awsdatacatalog database but in this repo database is not optional. So this MR handles this edge case.
You can create the below files in your personal dbt project. Alternatively you can clone the [sample project](https://github.com/Avinash-1394/dbt-athena-development) I created. Afterwards …
=> fix: Utilize cache for snapshots

README.md, dbt/adapters/athena/impl.py, dbt/include/athena/macros/materializations/models/table/create_table_as.sql, dbt/include/athena/macros/materializations/models/table/table_hive_ha.sql, dev-requirements.txt, tests/unit/test_adapter.py, tests/unit/utils.py
Add a new materialisation called `table_hive_ha` that extend the create_table_as, but with a not destructive behavior.
If the table is created for the first time it works like a normal table materialization.
If the table already exist, it create a tmp table (with the same attribute as the target relation), and then it uses a glue table swap that just point the target table to the new tmp table location.
If everything is successful the old table location is pruned, and the tmp table is dropped (note only catalog/glue definition).
To test that the materialization was working as expected I used this piece of code:
```
from pyathena import connect
import boto3
import os
os.environ['AWS_PROFILE'] = 'bi-staging'
session = boto3.session.Session(region_name='eu-central-1')
cursor = connect( …
```
=> feat: add table_hive_ha materialization

dbt/include/athena/macros/materializations/models/table/table_hive_ha.sql
I was just testing #128  but encountered an issue.
I was trying to create a model `test.sql` within the schema `migration_test`
But that would throw me an error which seemed weird.
`botocore.errorfactory.InvalidRequestException: An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: line 1:22: mismatched input '"migration_test"' expecting `
I was able to fix it by adding a `.render_hive()` to the `tmp_relation`s in the DDL queries within the new `table_hive_ha.sql`
```
{{ config(
materialized='table_hive_ha',
s3_data_naming='schema_table_unique'
) }}
select 
2 as inte
, cast('2022-12-12 12:12:12' as timestamp) as ts
, 'asd' as str
, 2.2 as double
, 1=1 as bool
```
=> fix: Render relation in Hive format for materialized='table_hive_ha'

dbt/adapters/athena/query_headers.py, dbt/adapters/athena/relation.py, dev-requirements.txt, tests/unit/test_relation.py
Optimize commands and vacuum need to be excluded from query header, but also they require rendering without quotes.
This PR add a simple function called `render_pure` that can be call when needed.
Tested with post_hooks
```
post_hook = [
"""
optimize {{this.render_pure()}} rewrite data using bin_pack
"""
]
```
Calling the method render_pure on the relation avoid to have quotes of any type, and let the command going through.
=> fix: allow optimize commands

dbt/adapters/athena/impl.py
Fixes `An error occurred (EntityNotFoundException) when calling the GetTables operation: Database my_db not found.` when listing relations. This assumes that the database already exists at runtime. 
This fix returns an empty relation when the database doesn't exist, similar to the default implementation in `dbt-core`. This allows for dbt to create schemas/databases and manage them.
=> fix: allow schema/database to not exist when listing relations

README.md, dbt/adapters/athena/impl.py, dbt/adapters/athena/utils.py, dbt/include/athena/macros/adapters/persist_docs.sql, dbt/include/athena/macros/materializations/models/view/view.sql, tests/unit/test_adapter.py, tests/unit/test_utils.py
Closes #167 
Add the feature of persisting docs in Athena / Glue. This is possible using the `update_table` feature of Glue API. This feature is not supported for views because Athena does not support comment for view.
- `seeds/schema.yml`
```yaml
version: 2
seeds:
- name: countries
description: A mapping of two letter country codes to country names
columns:
- name: country_code
description: The ISO code
tests:
- unique
- not_null
- name: country_name
tests:
- unique
- not_null
```
- `seeds/countries.csv`
```csv
country_code,country_name
US,United States
CA,Canada
GB,United Kingdom
```
- `models/schema.yml`
```yaml
version: 2
models:
- name: persist_docs_table
description: |
A test table to check whether or not we need to adjust persist doc. 
I can try to put simple quote ' or even double …
```
=> feat: add persist_docs

dbt/include/athena/macros/materializations/models/incremental/column_helpers.sql
fix https://github.com/dbt-athena/dbt-athena/issues/172 
alert statements must use `render_hive()` to escape the table with a backtick
run first this model
```
{{ config(
incremental_strategy='merge',
unique_key='user_id',
on_schema_change='append_new_columns',
table_properties={
'vacuum_max_snapshot_age_seconds': '86400',
'optimize_rewrite_delete_file_threshold': '2'
}
) }}
select
'a' as user_id,
{{ current_timestamp() }} as updated_at,
{{ current_timestamp() }} as inserted_at
```
then run this model
```
{{ config(
incremental_strategy='merge',
unique_key='user_id',
on_schema_change='append_new_columns',
table_properties={
'vacuum_max_snapshot_age_seconds': '86400', …
```
=> fix: add render hive in alter statements

dbt/adapters/athena/impl.py, dbt/include/athena/macros/adapters/columns.sql, dbt/include/athena/macros/adapters/metadata.sql, tests/unit/test_adapter.py, tests/unit/utils.py
Use Glue API instead of Athena information_schema to get info about tables and columns.
[These](https://github.com/dbt-athena/dbt-athena-development/pull/2) models
=> feat: use glue api instead of information_schema to retrieve table info

README.md, dbt/adapters/athena/connections.py, dbt/adapters/athena/impl.py, dbt/include/athena/macros/materializations/models/incremental/incremental.sql, dbt/include/athena/macros/materializations/models/table/table.sql, dbt/include/athena/macros/materializations/models/view/create_or_replace_view.sql, dbt/include/athena/macros/materializations/seeds/helpers.sql, pyproject.toml, tests/unit/test_adapter.py
Extend lake formation tags adding feature from [PR](https://github.com/dbt-athena/dbt-athena/pull/159) with possibility to set LF tags for columns.
Part of https://github.com/dbt-athena/dbt-athena/issues/22
Here is example model config, `lf_tags_columns` config is same for all materialisation options: table, incremental, view, seed.
```
{{
config(
incremental_strategy='append',
on_schema_change='append_new_columns',
lf_tags_columns={'my_tag_key': {'my_tag_value': ['column_name_1']}}
)
}}
```
=> feat: lakeformation tags for columns support

dbt/adapters/athena/impl.py, tests/unit/test_adapter.py
Iceberg support schema evolution, therefore columns can be dropped and added.
If we drop a column the column is somehow returned by the glue api, but it has an atrribute that can be used to pick only current columns. 
This PR aim to fix this issue.
model: iceberg_testing
```
{{ config(
incremental_strategy='append',
) }}
SELECT
'example'  as name,
1 as user_id,
cast(replace(cast(at_timezone(current_timestamp, 'Europe/Berlin') as varchar), ' Europe/Berlin', '') as timestamp(6)) as inserted_at
```
* then go run this `ALTER TABLE iceberg_testing DROP COLUMN inserted_at`
* then run the new model removing inserted_at
```
{{ config(
incremental_strategy='append',
) }}
SELECT
'example'  as name,
1 …
```
=> fix: Ignore iceberg columns that are not current

dbt/adapters/athena/impl.py, tests/unit/test_adapter.py
=> fix: return empty if table does not exist in get_columns

dbt/adapters/athena/impl.py
This fix prevent to fetch the "workgroup" location, if no workgroup is set in the profiles.
If so, `get_work_group_output_location` returns None, and the "location" of the workgroup won't be used.
=> fix: check for empty workgroup in profiles

dbt/adapters/athena/column.py, dbt/adapters/athena/impl.py, dbt/adapters/athena/relation.py, tests/unit/test_adapter.py
I'm trying to use `dbt_utils.union_relations` macro, but I get the following error:
TYPE_MISMATCH: line 11:6: Unknown type: string
Same error for types binary and timestamp.
The `AthenaColumn` class is implemented which resolves the problem with col.data_type attribute.
I've created 2 source models:
```
create table "sandbox"."tbl1"
with (
is_external=false,
location='s3://<bucket_name>/dbt/sandbox/tbl1',
format='parquet'
)
as
select 
localtimestamp(6) as ts,
'abc' as txt,
cast(12.23 as decimal(18,2)) as dcml,
from_hex('34c5b859b4764c0da59cca7675a74fbe') as bnr
```
```
create table "sandbox"."tbl2"
with (
is_external=false,
location='s3://<bucket_name>/dbt/sandbox/tbl2',
format='parquet'
)
as
select 
localtimestamp(6) as ts,
'abc' as txt, …
```
=> fix: glue column types

setup.py
Fixing this charcode error
Tried to build the main branch but got:
```
Updating dependencies
Resolving dependencies...
Unable to determine package info for path: D:\repos\tqa_dbt_models\.venv\src\dbt-athena
Fallback egg_info generation failed.
Command ['.venv\\Scripts\\python.exe', 'setup.py', 'egg_info'] errored with the following return code 1
Output:
Traceback (most recent call last):
File ".venv\src\dbt-athena\setup.py", line 10, in <module>
long_description = f.read()
^^^^^^^^
File "...AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 23, in decode
return codecs.charmap_decode(input,self.errors,decoding_table)[0]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 17701: character maps to …
```
=> fix: reading README.md

dbt/include/athena/macros/materializations/models/table/create_table_as.sql
Iceberg CTAS failed when `location` is not set although the used WorkGroup enables "Override client side settings".
Using and forcing the query result path of WorkGroup works only if Table Type is Hive.
=> fix: Iceberg CTAS failed when WG config is enforced

dbt/adapters/athena/impl.py, tests/unit/test_adapter.py, tests/unit/utils.py
This address this issue: https://github.com/dbt-athena/dbt-athena/issues/240
There are some edge cases when tables are created by api, where table type is not set, this pr uses a fallback to table in those cases, as it's the best assumption.
=> fix: use table as default type when building the catalog

dbt/adapters/athena/impl.py, dbt/adapters/athena/relation.py, dbt/include/athena/macros/adapters/relation.sql, dbt/include/athena/macros/materializations/models/table/create_table_as.sql, dbt/include/athena/macros/materializations/models/table/table.sql, tests/unit/test_adapter.py
This PR resolves #73. I had to add an extra parameter to the `AthenaRelation`, called `s3_path_table_part` to have the table stored in the correct location.
```sql
{{ config(
materialized='table',
partitioned_by=['hour(ts)'],
table_properties={
'vacuum_max_snapshot_age_seconds': '86400',
'optimize_rewrite_delete_file_threshold': '2'
}
) }}
SELECT cast(t.ts AS timestamp(6)) AS ts
FROM
unnest(
sequence(
current_date - INTERVAL '1' DAY,
cast(REPLACE(cast(current_timestamp as varchar), ' UTC', '') as timestamp(6)),
INTERVAL '1' MINUTE
)
) AS t(ts)
```
- [] You added functional testing when necessary
=> feat: add iceberg high availability on table using rename

dbt/adapters/athena/impl.py, tests/unit/constants.py, tests/unit/test_adapter.py
Resolves #247. 
The adapter method `_get_one_catalog` didn't account for the schema database when it was passed in the `schema.yml` file. Now if catalog_id is not `awsdatacatalog`, `_get_one_catalog` will get the catalog_id/database from the information_schema.
=> fix: check for database in _get_one_catalog (#247)

Makefile, README.md, requirements.txt
- The requirements.txt file and the `install_require` of setup.py were identical
- dbt adapter template has no requirements.txt and only a setup.py
=> chore: remove file requirements.txt to keep it consistent with adapter template

dbt/include/athena/macros/utils/timestamps.sql
Hi team,
First of all, thanks a lot for what you are doing with this adapter. I'm really fascinated with your pace of implementing new important fratures.
Unfortunately bugfix #235 introduced new bug: now `dbt source freshness` does not work at all.
Looks like `config` field is not propagated to `model` object of source in timestamp macro.
=> fix: source freshness (cast_timestamp for models without config field)

.github/workflows/functional-tests.yml
Functional tests are not accessing secrets from fork triggers or via dependantbot, this pr use pull_request_target at our own risk.
=> fix: functional test trigger fix

dbt/include/athena/macros/materializations/models/table/table.sql
Fix broken behavior for ha tables that was breaking in the first run, checking if the old table don't exists.
=> fix: ha=true for tables was broken for first runs

.github/workflows/functional-tests.yml
In the current CI implementation of functional tests, we were able to trigger them only on:
* merge to main
* when  the  label `enable-functional-tests`  was added to the PR
But in reality, we want to trigger functional tests run also in all the cases where the PR is labelled, not only on the action of labeling.
Fix found thanks to [this](https://stackoverflow.com/questions/62325286/run-github-actions-when-pull-requests-have-a-specific-label):
=> fix: handle how edge cases in functional tests triggering

.github/workflows/functional-tests.yml
After some back and forth on my private CI setup, I managed to have the right settings.
With the proposed changes the pipeline gets trigger on these conditions:
* on pull request if it has the label enable-functional-tests.
* trigger works when the label is added, when the there is a synchronize or something change
* on merge/push to main
=> fix: yet another fix on functional tests trigger

.github/workflows/functional-tests.yml, dbt/include/athena/macros/materializations/snapshots/snapshot.sql
When using pull_request_target GITHUB_REF, the default branch used in the checkout step, was set always to refs/head/main, but when running the tests on pr, this means that we were not able to spot the issues, as shown by this https://github.com/dbt-athena/dbt-athena/pull/313 - functional tests were ✅ , we merge it, and then we saw main broken.
This fix uses the GITHUB_HEAD_REF - that is set only for a pr, and if GITHUB_HEAD_REF is not set (e.g. merging to main), we pick GITHUB_REF.
=> fix: functional test edge case github ref

.github/workflows/functional-tests.yml
Create 2 separate jobs for PR and main branch, ugly as fuck but no time to implement the same workflow. We need to improve later on.
=> fix: seprate jobs for pr and main

README.md, dbt/adapters/athena/impl.py, dbt/adapters/athena/lakeformation.py, dbt/include/athena/macros/materializations/models/incremental/incremental.sql, dbt/include/athena/macros/materializations/models/table/table.sql, dbt/include/athena/macros/materializations/models/view/create_or_replace_view.sql, dbt/include/athena/macros/materializations/seeds/helpers.sql, dbt/include/athena/macros/materializations/snapshots/snapshot.sql, dbt/include/athena/sample_profiles.yml, tests/functional/adapter/test_snapshot.py
- `lf_tags` and `lf_tags_columns` configs support only attaching lf tags to corresponding resources.
We recommend managing LF Tags permissions somewhere outside dbt. For example, you may use
[terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lakeformation_permissions) or [aws cdk](https://docs.aws.amazon.com/cdk/api/v1/docs/aws-lakeformation-readme.html) for such purpose.
- `data_cell_filters` management can't be automated outside dbt because the filter can't be attached to the table
which doesn't exist. Once you `enable` this config, dbt will set all filters and their permissions during every
dbt run. Such approach keeps the actual state of row level security configuration actual after every dbt run and
apply changes if they occur: drop, create, …
=> feat: AWS LakeFormation data cell filters support

.github/workflows/functional-tests.yml
As agreed with @mattiamatrix  to keep AWS cost low, let's remove some regions.
Specifically:
* us-east-1 is kept as quite some new features are pushed there - similar to eu-west-1
* eu-central-1 as we want to have a region in Europe that is used by users, and where upgrades are not coming so often.
=> chore: trim regions for functional testing

dbt/include/athena/macros/materializations/seeds/helpers.sql
This is hotfix for athena__create_csv_table macro to avoid the following error:
```
09:57:59  Compilation Error in seed ref_action_type (seeds/ref_sources/ref_action_type.csv)
09:57:59    'relation' is undefined
```
=> fix: Lakeformation tags in athena__create_csv_table macro

dbt/adapters/athena/connections.py
Related issue: https://github.com/apache/airflow/issues/21605
When running dbt with Airflow KubernetesPodOperator there is an issue with logs fetching and current PR is fixing it with adding query state logging.
=> feat: Add Athena query state logging

dbt/adapters/athena/connections.py, tests/unit/test_connection_manager.py
This PR adds the field `data_scanned_in_bytes` to the adapter response, which allows for monitoring of Athena costs per DBT project/model/etc., see #335.
Tested by running some models from my own DBT project and comparing the output of 
```
cat target/run_results.json |  jq '.results[].adapter_response.data_scanned_in_bytes'
```
with the query stats from Athena console -> results checked out.
=> feat: add data_scanned_in_bytes to adapter response

dbt/adapters/athena/connections.py
Fixes #359 
Currently, the Glue catalog value is not being passed as a parameter in the AthenaConnection call.
When attempting to use a catalog other than the default (awsdatacatalog), the following error is displayed:
```
botocore.errorfactory.InvalidRequestException: An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: Unsupported ddl with 2 catalogs: ...*/
```
The solution now includes the addition of the 'catalog_name' parameter to the AthenaConnection handle.
=> feat: add catalog_name param to AthenaConnection handle

README.md, dbt/adapters/athena/impl.py, dbt/include/athena/macros/adapters/persist_docs.sql, dbt/include/athena/macros/materializations/models/view/view.sql
Since Athena view is just a Glue table it's an omission that persist_docs feature is disabled for views. It works exactly the same as with Athena tables.
=> fix: enable persist_docs for views

dbt/include/athena/macros/materializations/models/table/table.sql, tests/functional/adapter/test_change_relation_types.py
resolve #366
standard base tests
- [/] You followed [contributing section](https://github.com/dbt-athena/dbt-athena#contributing)
- [/] You kept your Pull Request small and focused on a single feature or bug fix.
- [/] You added unit testing when necessary
- [/] You added functional testing when necessary
=> fix: failure when config from view to Iceberg table

dbt/adapters/athena/connections.py, dbt/adapters/athena/impl.py, dbt/include/athena/macros/materializations/models/helpers/get_partition_batches.sql, dbt/include/athena/macros/materializations/models/incremental/helpers.sql, dbt/include/athena/macros/materializations/models/incremental/incremental.sql, dbt/include/athena/macros/materializations/models/incremental/merge.sql, dbt/include/athena/macros/materializations/models/table/create_table_as.sql, dbt/include/athena/macros/materializations/models/table/table.sql
Resolves: https://github.com/dbt-athena/dbt-athena/issues/87 
For table materialization (iceberg):
```
{{
config(
schema='sandbox',
materialized='table',
partitioned_by=['DAY(date_column)', 'doy'],
table_type='iceberg'
)
}}
SELECT
CAST(date_column AS DATE) as date_column,
doy(date_column) as doy,
random() as rnd
FROM (
VALUES (
SEQUENCE(FROM_ISO8601_DATE('2023-01-01'), FROM_ISO8601_DATE('2023-07-24'), INTERVAL '1' DAY)
)
) AS t1(date_array)
CROSS JOIN UNNEST(date_array) AS t2(date_column)
```
For table materialization (hive):
```
{{
config(
schema='sandbox',
materialized='table',
partitioned_by=['date_column', 'doy'],
table_type='hive'
)
}}
SELECT
random() as rnd,
CAST(date_column AS DATE) as date_column,
doy(date_column) as doy
FROM (
VALUES (
SEQUENCE(FROM_ISO8601_DATE('2020-01-01'), …
```
=> feat: fix athena partitions limit

.github/CODEOWNERS, .github/workflows/ci.yml, README.md, dbt/adapters/athena/__version__.py, dev-requirements.txt, setup.py, tests/conftest.py, tests/functional/adapter/fixture_split_parts.py, tests/functional/adapter/utils/test_utils.py
* Bump dbt core to 1.6.0
* drop support for Python 3.7
No major change in the adapter so far. The only feature worth adding is `dbt clone` - we should consider to do it separately .
=> chore: bump dbt-core to 1.6.0

dbt/adapters/athena/connections.py, dbt/adapters/athena/impl.py, dbt/include/athena/macros/materializations/models/incremental/helpers.sql, dbt/include/athena/macros/materializations/models/incremental/incremental.sql, dbt/include/athena/macros/materializations/models/incremental/merge.sql, dbt/include/athena/macros/materializations/models/table/create_table_as.sql, dbt/include/athena/macros/materializations/models/table/table.sql, dev-requirements.txt, tests/functional/adapter/test_partitions.py
Fix https://github.com/dbt-athena/dbt-athena/issues/374
This approach doesn't cover cases where we do batch inserts due to partition limitations.
=> fix: add back rowcounts and byte scanned to dbt cli and run_results.json

dbt/adapters/athena/connections.py
connection's `handle` field is [PyAthena's Connection instance](https://github.com/laughingman7743/PyAthena/blob/master/pyathena/connection.py). This instance doesn't have `cancel` method. So we should avoid calling it.
=> fix: avoid calling cancel method not implemented in PyAthena's connection

dbt/adapters/athena/impl.py
I'd like to get a list of table in a schema/database from a macro. This PR proposes to make `list_relations_without_caching` available as the database method for the parser.
=> fix: Mark list_relations_without_caching as available

README.md, dbt/adapters/athena/connections.py, dbt/adapters/athena/impl.py, dbt/adapters/athena/lakeformation.py, dbt/include/athena/macros/adapters/schema.sql, tests/unit/test_lakeformation.py
Add config to assign default tags for database if it's created by DBT.
Resolves: https://github.com/dbt-athena/dbt-athena/issues/373
=> feat: Implement default lf tags for database

dbt/include/athena/macros/materializations/models/table/create_table_as.sql
Small fix to put the actual relation in the logging.
Before fix
```
{{ relation }} with many partitions created
```
After fix
```
'"awsdatacatalog"."dbt_nicola"."test_partitions" with many partitions created';
```
=> fix: render relation in case of we hit partition limits

.gitignore, dbt/include/athena/macros/materializations/models/helpers/get_partition_batches.sql, dbt/include/athena/macros/materializations/models/incremental/incremental.sql, dbt/include/athena/macros/materializations/models/table/create_table_as.sql
Resolves: https://github.com/dbt-athena/dbt-athena/issues/396
Currently we have partitioned temp table creation for table and increment materialisation.
However this can lead to over price and over resources consumption as model's sql can be complicated. So that batches split run on this complicated sql may be not the very optimal way.
This PR implements the logic when we skip partitioning config while creating new tmp table and then we calculate batches and run insert statement based on this non-partitioned table.
table iceberg
```
{{
config(
schema='test_schema',
materialized='table',
partitioned_by=['DAY(date_column)', 'doy'],
table_type='iceberg'
)
}}
SELECT
CAST(date_column AS DATE) as date_column,
doy(date_column) as doy,
random() as rnd
FROM (
VALUES ( …
```
=> feat: Implement non-partitioned tmp table

dbt/include/athena/macros/materializations/models/incremental/merge.sql, tests/functional/adapter/test_incremental_iceberg.py, tests/functional/adapter/test_incremental_iceberg_merge_no_updates.py
Incremental model may have `unique_key` same as `merge_update_columns`. For example, to skip updates for matched rows and do only inserts and/or deletes. In such cases, the generate merge sql statement is invalid:
```sql
merge into alerts as target using alerts__dbt_tmp as src
on (target.alert_id = src.alert_id)
when matched
then update set
when not matched
then insert  (...)
values (...)
```
Another case when the update column list can be empty and generate similar invalid sql is if `merge_exclude_columns` removes all columns.
The fix checks the final update list and uses it only if it's not empty, avoid generating incomplete `when matched then update` part of the merge statement.
The PR adds 2 tests to cover both cases. As I don't see any ready test to cover `merge_update_columns` …
=> fix: Invalid merge when unique_key == merge_update_columns

dbt/include/athena/macros/adapters/columns.sql, tests/functional/adapter/test_constraints.py
Resolve a error when a model has a pre-reserved named column.
Related PR: https://github.com/dbt-labs/dbt-core/pull/7537.
The functional test does not check the exact sql by historical reasons.
Please check a comment on the code.
https://github.com/dbt-labs/dbt-core/blob/5182e3c40c9aadcafdb77e7fdcd6091ae0277444/tests/adapter/dbt/tests/adapter/constraints/fixtures.py#L256-L261
```sql
select
'blue' as "from",
1 as id,
'2019-01-01' as date_day
```
https://github.com/dbt-labs/dbt-core/blob/5182e3c40c9aadcafdb77e7fdcd6091ae0277444/tests/adapter/dbt/tests/adapter/constraints/fixtures.py#L501-L529
```sql
version: 2
models:
- name: my_model
config:
contract:
enforced: true
materialized: table
constraints:
- type: check
expression: ("from" = 'blue')
columns: [ '"from"' ]
columns:
- name: id …
```
=> feat: support quoted columns in constraint

dbt/adapters/athena/impl.py
Add `AthenaConfig` to `impl.py` following [recommendations](https://docs.getdbt.com/guides/dbt-ecosystem/adapter-development/3-building-a-new-adapter)
I have added the [Table configuration](https://github.com/dbt-athena/dbt-athena) as well as the connection parameters that can be passed to `cursor.execute()`
This might help to resolve https://github.com/dbt-athena/dbt-athena/issues/377, but it doesn't fix it by itself
I ran the unit tests locally and they all passed
I ran some of the functional tests and they passed too, but I didn't run all of them
=> chore: add AthenaConfig to impl.py

dbt/include/athena/macros/materializations/models/helpers/get_partition_batches.sql
Our functional tests were failing, specifically, the failures seem due only to cases where we deal with partitions and partitions being integers.
In case we one partition that is an integer, `adapter.convert_type` returns None, not integer, as you can see from [here](https://github.com/dbt-labs/dbt-core/compare/v1.6.2...v1.6.3#diff-2eee7e45ddbdac7ecdd8458a1c8c6b0d6d0c7dc6169e321eb2ab7a537f4171b1R20-R21).
This PR treats integers and None types equally - assuming that None types are actually integer.
This issue should be actually fixed in dbt-core, but for now we add this workaround.
=> fix: improve get_partition_batches to treat integers properly

dbt/include/athena/macros/materializations/models/incremental/helpers.sql
Fix incremental updates for tables with the `insert_overwrite` strategy and `int` partition columns when using dbt-core==1.6.3. Otherwise updates fail with:
```
can only concatenate str (not "NoneType") to str
> in macro materialization_incremental_athena (macros/materializations/models/incremental/incremental.sql)
> called by ...
```
The root cause is exactly as in https://github.com/dbt-athena/dbt-athena/pull/425 (`convert_type()` returns None for int columns)
This PR adds the same workaround to `delete_overlapping_partitions()`. 
```sql
{{
config(
materialized = 'incremental',
incremental_strategy = 'insert_overwrite',
partitioned_by = ['m']
)
}}
select 'val' as val, 1 as m
```
=> fix: insert_overwrite updates for tables with int partitions

RELEASING.md, dbt/adapters/athena/__version__.py
* Bump for release
* Add REALISING.md
=> chore: release v1.6.3

dbt/adapters/athena/impl.py, dbt/adapters/athena/utils.py, tests/unit/test_utils.py
Hi team, I suggest improvement which should significantly improve data observability from my point of view.
If `persist_docs` is enabled we write additional metadata to Glue Table Properties:
- all fields from `model.config.meta` (i.e. owner, unique_key, other custom fields)
- `model.config.materialized` value (to mark incremental tables)
- dbt project name and version (to identify tables depoyed via dbt and find outdated tables by project version)
This improvement allows to treat Glue Catalog as a storage of tabel metadata and build interactive application around it without need to access dbt manifest.
Tested on view, table, incremental table
=> feat(persist_docs): write dbt model and project metadata to properties

dbt/adapters/athena/impl.py
Currently it is impossible to successfully run dbt docs generate if you referencing table with CAPITALIZED NAME from external Data Catalog as a dbt source.
This because under the hood boto3 returns original table name, but source name are being converted to lower case somewhere in dbt core.
=> fix(docs): generate docs for Federated Data Sources with capitalized table names

dbt/adapters/athena/connections.py, dbt/adapters/athena/session.py
Resolves https://github.com/dbt-athena/dbt-athena/issues/458
This PR adds support for passing in the AWS session token to a profiles.yml file, allowing for the use of short term credentials.
=> feat: allow aws session token in profiles file

dbt/adapters/athena/impl.py
In `swap_table` we must use paginator to retrieve the partitions.
Missing pagination was leading to issue where only some partitions were deleted and it was causing  what described here https://github.com/dbt-athena/dbt-athena/issues/464 hence this should fix it.
=> fix: in swap_table we need to use get_partitions pagination

README.md, dbt/adapters/athena/impl.py, dbt/adapters/athena/lakeformation.py, dbt/include/athena/macros/materializations/models/incremental/incremental.sql, dbt/include/athena/macros/materializations/models/table/table.sql, dbt/include/athena/macros/materializations/models/view/create_or_replace_view.sql, dbt/include/athena/macros/materializations/seeds/helpers.sql, dbt/include/athena/macros/materializations/snapshots/snapshot.sql, tests/unit/test_lakeformation.py
See: #452
1. Associate a tag with a database
2. Configure tag in `dbt_project.yml`, for example: `+lf_inherited_tags: [my-tag]` within `models:`
3. Add an `lf_tags_config` to a model to set some other tags
4. Run the model and observe that e.g. `my-tag` is retained instead of being removed and that additional model-level tags are associated
=> feat: lf_inherited_tags config to exclude certain tags from CRUD

dbt/adapters/athena/impl.py, tests/unit/test_adapter.py
Added 'CatalogId' Parameter to the Glue Paginator Call
This PR adds the 'CatalogId' parameter to the Glue Paginator Call. It is related to the changes made in PR #370, which has already been merged.
=> fix: add 'CatalogId' Parameter to Glue Paginator Call (Related to PR #370)

dbt/adapters/athena/query_headers.py, tests/unit/test_query_headers.py
Fix MSCK REPAIR TABLE.
Fix when setting pre-hook: `MSCK REPAIR TABLE`, but got error as bellow:
[ErrorCategory:USER_ERROR, ErrorCode:DDL_FAILED], Detail:FAILED: ParseException line 1:216 cannot recognize input near '<EOF>' '<EOF>' '<EOF>'
Resolve #468
=> fix: bug when setting pre-hook=MSCK REPAIR TABLE

README.md, dbt/include/athena/macros/materializations/models/incremental/incremental.sql, dbt/include/athena/macros/materializations/models/incremental/merge.sql, tests/functional/adapter/test_incremental_iceberg.py
- This PR introduces insert condition for the merge strategy in the incremental run.
- Resolves [#466  ](https://github.com/dbt-athena/dbt-athena/issues/466)
```
{{ config(
incremental_strategy='merge',
unique_key=['id'],
insert_condition='src.status != 0'
)
}}
{% if is_incremental() %}
select * from (
values
(1, -1)
, (2, 0)
, (3, 1)
) as t (id, status)
{% else %}
select * from (
values
(0, 1)
) as t (id, status)
{% endif %}
```
=> feat: Implement insert condition for merge strategy.

.github/workflows/ci.yml
Force python version for pre-commits to python 3.11. Locally the pre-commit works for me, and the last merged PR used python 3.11.
=> fix(ci): make flake 8 working in the pre-commit

dbt/include/athena/macros/utils/timestamps.sql
We have a  table_type glue. But only table type: hive and iceberg are supported.
=> fix: change default table_type in cast_timestamp macro

dbt/include/athena/profile_template.yml
Adding a prompts in profile_template force the user to add the parameter, even if it's optional.
As we don't have a real default value for seed_s3_upload_args, we can simply remove it.
Closes https://github.com/dbt-athena/dbt-athena/issues/486
=> fix: remove seed_s3_upload_args

.github/workflows/functional-tests-workflow.yml, dbt/adapters/athena/__version__.py, dbt/adapters/athena/impl.py, dbt/include/athena/macros/adapters/metadata.sql, dev-requirements.txt, setup.py, tests/conftest.py, tests/functional/adapter/test_constraints.py, tests/functional/adapter/test_docs.py, tests/unit/test_adapter.py
Bump dbt to 1.7.0 and see what we break, close https://github.com/dbt-athena/dbt-athena/issues/454
Added functional tests for dbt docs and macro overwride.
> https://github.com/dbt-labs/dbt-core/issues/8846 is a pre-regression in 1.7.0rc1 that will be remediated for the final release of 1.7.0. The issue only impacts adapters that have overridden BaseAdapter.get_catalog() method. However, this does not affect adapters that have overridden the get_catalog(), macro.
Based on the code base we overwrite only get_catalog macro, but we don't overwrite, BaseAdapter.get_catalog(), but we overwrite a method that is called by get_catalog. 
References:
* [trino__get_catalog_relations](https://github.com/starburstdata/dbt-trino/blob/2e0cd5854f14127d59ac4fb356a67dde7884fce0/dbt/include/trino/macros/cata …
=> chore: bump dbt to 1.7.0

README.md, dbt/adapters/athena/config.py, dbt/adapters/athena/connections.py, dbt/adapters/athena/impl.py, tests/unit/test_config.py
This PR introduces a new functionality to the Athena adapter allowing users to specify a custom number of retry attempts for boto3 calls within the dbt-athena-community plugin. The modification adds a parameter to get_boto3_config function, enabling it to accept the number of retries as an argument. This change enhances resilience and configurability by letting users define their retry strategies, accommodating for network inconsistencies or AWS rate limits.
Resolves #480.
- Added a `num_retries` parameter to `get_boto3_config` function to accept custom retry attempts.
- Introduced `num_boto3_retries` as an optional configuration in `AthenaCredentials` to store the number of boto3 retries.
- `get_effective_num_retries` method in `AthenaCredentials` to determine the effective number of …
=> feat(athena-adapter): support custom retry configurations for boto3 calls

.github/workflows/functional-tests.yml
Use region as a variable for concurrency in our functional tests. The limitations are per region not per account.
=> chore: use region for concurrency functional tests

dbt/adapters/athena/impl.py, dbt/adapters/athena/relation.py, tests/functional/adapter/test_detailed_table_type.py, tests/unit/test_adapter.py, tests/unit/utils.py
In `dbt/adapters/athena/impl.py`, I've added new parameter to additionally handle the `table_type` attribute for Iceberg tables. The update add new optional parameter `detailed_table_type` which gets from Table["Parameters"]["table_type"] dictionary if it not exists - set `detailed_table_type` to `None`.
I've extended the AthenaRelation class in `dbt/adapters/athena/relation.py` to include a new optional attribute `detailed_table_type`. This attribute holds the specific type of table as described in the table's parameters in the Glue Catalog, providing more detailed context about the Athena relation.
Resolves: #511
=> feat: add `detailed_table_type` property to `list_relations_without_caching` function

dbt/include/athena/macros/materializations/models/view/view.sql
In our dbt runs we received the following error:
```
Number of TABLE_VERSION resources exceeds the account limit 1000000
```
Debugging led to the conclusion that views are creating new versions but old views are not cleaned up.
- internal views that had lots of versions, after `dbt run` with this change they are down to last 4 glue versions
=> fix: prune old versions also for views

dbt/adapters/athena/impl.py
Fix null as comment in columns after change in yml
Now, after changing a comment on a column, the comment is left only for the changed column.
Comments on other columns will be marked as null.
This situation has been fixed.
=> fix: Null as comment in columns after change in yml

dbt/adapters/athena/impl.py, dbt/include/athena/macros/adapters/persist_docs.sql, dbt/include/athena/macros/materializations/models/incremental/incremental.sql, dbt/include/athena/macros/materializations/models/view/view.sql
Related issue: https://github.com/dbt-athena/dbt-athena/issues/524
=> fix: Prune old table version for incremental models

.github/ISSUE_TEMPLATE/bug_report.yml
Issue template for bugs was not rendering
=> fix: wrong yml formatting in issue template for bugs

dbt/include/athena/macros/materializations/models/incremental/incremental.sql, dbt/include/athena/macros/materializations/models/table/table.sql
Implemented as discussed in #546.
Uses `adapter.get_relation` to search for an old tmp_relation that could exist if the previous table creation did not clean it up properly.
=> fix: check for old tmp table before deleting it

dbt/adapters/athena/impl.py, dbt/include/athena/macros/materializations/models/helpers/get_partition_batches.sql, dbt/include/athena/macros/materializations/models/helpers/process_bucket_column.sql, dev-requirements.txt, setup.py, tests/functional/adapter/test_partitions.py, tests/unit/test_adapter.py
Resolves: #529 
* Fix error `FUNCTION_NOT_FOUND: line 2:21: Function 'bucket' not registered` by adding regex for extract bucket column from `partitioned_by` config
* Implement `murmur3_hash` method to calculate bucket number of bucket column value as it works for Iceberg tables in Athena
* Implement support for more than 100 partitions when bucket function used into `partitioned_by` config for Iceberg tables
* Improve `get_partition_batches` macros with put bucket_column values to appropriate bucket number and than and add values to final WHERE condition for batches
Tested on next column types for `bucket` function:
Not works now for next types (needed additional implementation in dbt-athena-community adapter):
* Bytes
* UUID
* Decimal
```SQL
{{
config(
schema='sandbox', …
```
=> feat: Implement support bucket function for more than 100 partitions

dbt/include/athena/macros/materializations/models/view/create_or_replace_view.sql, dbt/include/athena/macros/materializations/models/view/view.sql
Resolves #564
During fix in #487 wasn't removed lf_inhered_tags parameter from create_or_replace_view.sql macros, that's why I get error when create view.
Described in #564
=> fix: remove lf_inherited_tags parameter from create_or_replace_view macros

dbt/include/athena/macros/materializations/hooks.sql
I found that there is a duplication of running hooks for incremental materialization.
This happens because of run_hooks macro which does not filter hooks list for different modes of inside_transaction:
```
{{ run_hooks(post_hooks, inside_transaction=True) }}
{{ run_hooks(post_hooks, inside_transaction=False) }}
```
Test model:
```
{{
config(
incremental_strategy='append',
post_hook="select 'DEBUG RUN_HOOK' as r",
)
}}
select 1 as id, cast('2024-01-01' as timestamp(6)) as event_ts;
```
=> fix: duplication of hooks in incremental materialization

dbt/include/athena/macros/materializations/models/table/create_table_as.sql, tests/functional/adapter/test_ha_iceberg.py
Fixes https://github.com/dbt-athena/dbt-athena/issues/597 and add functional tests to be sure that the behvior is catched systematically by tests
Bug was introduced in 1.7.2 by a typo in https://github.com/dbt-athena/dbt-athena/pull/560
See the functional tests added to test the behvior
=> chore: fix bug in iceberg materialization, and add iceberg ha tests

dbt/adapters/athena/connections.py
=> fix: Use dbt-core md5 to inheret FIPS compatibility

setup.py
- To enable compatibility with airflow 2.7, we would need to go down to 1.28
This might be the preferred solution, as this compatibility matrix suggests dbt-core~=1.7 is compatible with airflow~=2.7
https://astronomer.github.io/astronomer-cosmos/getting_started/execution-modes-local-conflicts.html#airflow-and-dbt-dependencies-conflicts
=> fix: downgrade boto3 for airflow 2.7 compatibility

dbt/include/athena/macros/materializations/hooks.sql
`optimize\W+\w+\W+rewrite data using bin_pack` does not match `optimize awsdatacatalog.db_name.fct_table_name__inc rewrite data using bin_pack` and therefor fails.
I was wondering why this does not work. But the current regex does not match <data_source>.<db_name>.<table_name>.
Can you maybe check on your end, why the regex was designed this way? Not too sure if I am missing sth.
My post hooks are:
```
...
s3_data_naming = 'schema_table_unique',
post_hook=['optimize {{ this }} rewrite data using bin_pack', 'vacuum {{ this }}'],
table_properties={
'optimize_rewrite_delete_file_threshold': '10'
}
)
```
=> fix: Optimize regex in post-hooks

setup.py
The current function in setup.py didn't allow to publish semnatic versions with prekind and pre. This of course affected the release of the the adapter for the beta release, consequently the published library was 1.8.0, that is actually not correct.
This PR fix the parsing, purely take from https://github.com/starburstdata/dbt-trino/blob/master/setup.py#L45-L50
=> fix: allow release to be beta

dbt/include/athena/macros/materializations/models/table/table.sql, tests/functional/adapter/test_hive_iceberg.py
Fixes https://github.com/dbt-athena/dbt-athena/issues/478
Also add functional tests to be sure that we can switch smoothly from hive to iceberg, and from iceberg to hive.
This can be really helpfull, to allow users to change table type easily without a full-refresh.
For the functional tests I did a sort of hack, where I pass the table_type via a `table_type` var, that then it's used in the config like this: `table_type=var("table_type"),` works fine.
Provided functional tests to cover the implementation
=> fix: allow switch from hive to iceberg table

dbt/adapters/athena/impl.py, tests/unit/test_adapter.py, tests/unit/test_query_headers.py
`list_relations_without_caching` continues even when an error occurs when paginating tables.
As a result, this function returns `relations` before collecting all the tables in a Glue database.
To avoid this, build full pagination before collecting tables in the loop.
Also, catch more precise errors about `ClientException`.
- Dissucssion on Slack: https://getdbt.slack.com/archives/C013MLFR7BQ/p1713756253589009
=> fix: avoid deleting S3 location because listing relations continues on error

dbt/adapters/athena/connections.py
Currently any fields returned by `_connection_keys` are considered safe to log while debugging. This could lead to these credentials being logged unintentionally.
=> feat: prevent secret key and session token from being logged

README.md, dbt/adapters/athena/impl.py, dbt/include/athena/macros/adapters/persist_docs.sql, tests/unit/test_adapter.py
Modify `persist_docs_to_glue()` so that it can update [glue column parameters](https://docs.aws.amazon.com/glue/latest/webapi/API_Column.html) based on dbt column meta.
For example:
```
version: 2
models:
- name: test_deduplicate
description: another value
config:
persist_docs:
relation: true
columns: true
meta: 
test: banana
columns:
- name: id
meta: 
primary_key: true
```
See [slack](https://getdbt.slack.com/archives/C013MLFR7BQ/p1715167910378029) for more details
Wasn't sure how to run `persist_docs_to_glue()` against my models
=> feat: Add column meta to glue column parameters

README.md
This PR adds a few of the limitations I found while trying to implement a Python model. It also cleans up some language in the docs and puts the sections in the correct order.
For reference, I have a Python model implementation here: https://github.com/ccao-data/data-architecture/pull/422.
=> docs: Cleanup Python models section of README

dbt/adapters/athena/__version__.py, dev-requirements.txt, setup.py
Prepare release 1.8.0.
As other adapters I added back dbt-core dependency in setup.py:
* [dbt-duckdb](https://github.com/duckdb/dbt-duckdb/blob/master/setup.py#L44)
* [dbt-bigquery](https://github.com/dbt-labs/dbt-bigquery/blob/main/setup.py#L64)
=> chore: prepare release 1.8.0

dbt/adapters/athena/__version__.py
When we released the 1.8.0b1 version, an issue with setup.py, lead to parse 1.8.0b1 incorrectly, causing an upload as 1.8.0.
We fixed the setup.py, [here](https://github.com/dbt-athena/dbt-athena/pull/624) and re-upload as 1.8.0b1, and remove 1.8.0 manually from pypi. Only to discover that we cannot republish 1.8.0
we release as 1.8.1
=> chore: release for 1.8.0 using 1.8.1

README.md
This PR cleans up some of the grammar, punctuation, and capitalization in the README. It also fixes some misspecified links (that I created! Oops), and tries to clarify some language. I've added some PR comments where I feel the README language is still unclear.
=> docs: Cleanup README grammar, punctuation, and capitalization

dbt/adapters/athena/connections.py
I've enabled elementary for my dbt projects. On the biggest one I'm running every dbt model as separate airflow task and I have problem on on-run-end hook level. When elementary tries to insert new data, the problem occurs on parallel model runs. I'm getting the following error
```
[2024-05-20, 11:37:52 UTC] {pod_manager.py:484} INFO - [base]   {'status': 'error', 'message': "on-run-end failed, error:\n ICEBERG_COMMIT_ERROR: Failed to commit Iceberg update to the table: . If a data manifest file was generated at 's3://.../results/dbt/f4ea24c3-29ec-43a7-bc46-a1fca4ece38c-manifest.csv', you may need to manually clean the data from locations specified in the manifest. Athena will not delete data in your account.", 'thread': 'main', 'execution_time': 0, 'num_failures': 1, 'timing_info': [], …
```
=> fix: Add wait_random_exponential for query retries

dbt/include/athena/macros/materializations/models/view/create_or_replace_view.sql, tests/functional/adapter/test_python_submissions.py
Currently, it is not possible to clone Python models using `dbt clone` because of [an outdated reference in the `create_or_replace_view` macro](https://github.com/dbt-athena/dbt-athena/blob/34633a7f5679344852d1004991fc814ab385dadb/dbt/include/athena/macros/materializations/models/view/create_or_replace_view.sql#L32) to a [`sql` context variable](https://github.com/dbt-labs/dbt-core/blob/d21ff38ba1aafdee67e0165856f59b31d824d144/core/dbt/context/providers.py#L1513-L1519) that returns `None` for Python models. This PR represents a one-line change to update that reference to the newer [`compiled_code` context variable](https://github.com/dbt-labs/dbt-core/blob/d21ff38ba1aafdee67e0165856f59b31d824d144/core/dbt/context/providers.py#L1501-L1511) that implements the exact same logic as `sql` but …
=> fix: Resolve error when cloning Python models (#645)

CONTRIBUTING.md, README.md, dbt/adapters/athena/impl.py, dbt/include/athena/macros/materializations/models/incremental/incremental.sql, tests/functional/adapter/test_unique_tmp_table_suffix.py
For some specific cases (eg. backfill very large amount of data), we need to execute parallel multiple `dbt build` of specific incremental model in which we pass the date (or batch number) as var argument.
For example, we have a model we run every hour using Airflow for which we pass the a date relative to the Airflow scheduler.
If we want to process by batch of N hours in parallel using Airflow concurrency, we need the tmp table create by each of the dbt run to be unique. Else, you are going to end up with N insert attempting to run with the same `__dbt_tmp` name, creating conflict and ultimately creating failure.
Similar issue open here: https://github.com/Tomme/dbt-athena/issues/62
Second (incremental) run model output:
```sql
-- /* {"app": "dbt", "dbt_version": "1.8.0", …
```
=> feat: Set unique table suffix to allow parallel incremental executions

dbt/adapters/athena/impl.py, dbt/adapters/athena/relation.py, tests/unit/test_adapter.py, tests/unit/test_relation.py
with following table
```
{'Name': 'test', 'DatabaseName': 'raw', 'Owner': 'hadoop', 'CreateTime': datetime.datetime(2022, 3, 8, 15, 49, 45, tzinfo=tzlocal()), 'UpdateTime': datetime.datetime(2022, 3, 8, 15, 49, 45, tzinfo=tzlocal()), 'LastAccessTime': datetime.datetime(1970, 1, 1, 1, 0, tzinfo=tzlocal()), 'Retention': 0, 'StorageDescriptor': {'Columns': [{'Name': 'brand', 'Type': 'string'}, {'Name': 'dt', 'Type': 'timestamp'}], 'Location': 's3://stage-dwh-transformed/brand_governed', 'InputFormat': 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat', 'OutputFormat': 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat', 'Compressed': False, 'NumberOfBuckets': -1, 'SerdeInfo': {'SerializationLibrary': 'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe', …
```
=> fix: Fixed table_type for GOVERNED tables

README.md
Closes #628 
Documentation update to README.md to inform the user about populating the locating table in AWS Glue for python models.
=> chore: Added information about location table to readme (#628)

dbt/include/athena/macros/materializations/models/table/table.sql, tests/functional/adapter/test_ha_iceberg.py
See https://getdbt.slack.com/archives/C013MLFR7BQ/p1717497450266499
Pretty much https://github.com/dbt-athena/dbt-athena/pull/625 introduced a regression that was not letting iceberg working in an full high available mode.
This PR cover the issue, and add functional tests to catch these edge case.
Plus it introduce some improvements that allow to work properly in some restrictive LF permission models, where drop can happen only on existing objects.
See functional tests
=> fix: edge case fix on iceberg target table being dropped instead on being renamed first

dbt/adapters/athena/column.py, tests/unit/test_column.py
`AthenaColumn` is used to parse column metadata returned by Glue, particularly in [`AthenaAdapter.get_columns_in_relation()`](https://github.com/dbt-athena/dbt-athena/blob/7d850524d3a4f80635dcdeb71684bf8ef0a03b16/dbt/adapters/athena/impl.py#L1140-L1142). The [`AthenaColumn.data_type`](https://github.com/dbt-athena/dbt-athena/blob/7d850524d3a4f80635dcdeb71684bf8ef0a03b16/dbt/adapters/athena/column.py#L48-L62) property method is configured to convert a number of [DDL data types](https://docs.aws.amazon.com/athena/latest/ug/data-types.html) to their DML equivalent (e.g. `string` ➡️ `varchar`), but it is not yet configured to convert array types, meaning that any code that consumes column definitions from `get_columns_in_relation` can raise errors like this one:
```
TYPE_MISMATCH: Unknown …
```
=> feat: Update `AthenaColumn` to parse array types

dbt/adapters/athena/impl.py
Fixes #676
This moves client creation into the cached method, which makes the lru_cache depend only on the work_group name (which it has to depend on, as that drives the output) and the AthenaAdapter instance (via `self`, which is instantiated once per dbt thread it seems) but not the athena client (which gets instantiated once per lookup in the original implementation).
=> fix: Improve caching of work_group lookup

dbt/adapters/athena/relation.py, tests/functional/adapter/test_ha_iceberg.py, tests/functional/adapter/test_hive_on_schema_change.py, tests/functional/adapter/test_on_schema_change.py, tests/unit/test_relation.py
This resolves #677 
When generating Hive DDL, the relation spec must not include the catalog name (i.e. "awsdatacatalog"), only the database (schema) and table name. #677 discovered that the DDL generated when `on_schema_change` is set to `sync_all_columns` generates `alter table awsdatacatalog.schema_name.table_name replace columns (…)` (with backticks around the relation spec components, but I don't know how to make Markdown include literal backticks). This DDL fails with a syntax error.
I don't know why all DDL doesn't fail, why this was only a problem when `on_schema_change` is set to `sync_all_columns`. For example, I can see multiple `ALTER TABLE … SET TBLPROPERTIES …` that are run when I run the functional tests, and none of them have the catalog in the relation spec.
My fix makes …
=> fix: Remove catalog from the DDL SQL generated by on_schema_change=sync_all_columns

dev-requirements.txt
Reverts dbt-athena/dbt-athena#692
=> fix: Revert "chore: Update pyupgrade requirement from ~=3.16 to ~=3.17"

dbt/adapters/athena/impl.py, dbt/adapters/athena/query_headers.py
Resolve #701 
Insert query comment for queries with `vacuum_*` configs
Any model with `vacuum_max_snapshot_age_seconds: 86400`
=> fix: Query comment for create table statement

dbt/adapters/athena/query_headers.py, tests/unit/test_query_headers.py
Resovles #704 
On post-hook operation vacuum, optimize presented leading whitespaces in query, even if you config looks like this:
```yaml
+post-hook:
- "vacuum {{ this }}"
- "optimize {{ this }} rewrite data using bin_pack"
```
So,  lstrip() method fix it
=> fix: remove leading whitespaces on post-hook operations

dbt/adapters/athena/impl.py, dbt/include/athena/macros/materializations/hooks.sql
When there is too many files to process during a vacuum, dbt model fails with this error: "ICEBERG_VACUUM_MORE_RUNS_NEEDED: Removed 20000 files in this round of vacuum, but there are more files remaining. Please run another VACUUM command to process the remaining files."
We apply therefore the same logic as we did for the optimize. There is also an attempt to gather the code since they have the same logic.
=> fix: vacuum more runs needed error

README.md, dbt/adapters/athena/connections.py, dbt/adapters/athena/impl.py, tests/unit/test_adapter.py
The adapter performs a GetWorkGroup operation on each thread, which is later cached. When dbt build is started for 10 independent models, it issues 10 AWS requests to get the same information. If dbt is orchestrated via Airflow to run 32 dbt tasks concurrently, it sends 320 GetWorkGroup requests, causing throttling on the AWS side.
This PR introduces a skip_workgroup_check setting, which instructs dbt to skip checking if a WorkGroup contains an enforced output location.
=> feat: skip_workgroup_check setting to reduce AWS throttling

dbt/adapters/athena/impl.py, tests/functional/adapter/test_docs.py
Remove non-current iceberg columns from catalog
```
{{
config(
materialized="table",
table_type="iceberg",
post_hook="alter table model drop column to_drop"
)
}}
select 1 as id, 'to_drop' as to_drop
```
Previously, `dbt docs generate`  command generated `catalog.json` artifact which included `to_drop` column as well, however it did not exist in current table version.
Current PR fixes this behaviour and stores in `catalog.json` file only actual columns.
=> fix: Remove non-current iceberg columns from catalog

.github/workflows/publish-internal.yml
The PyPI version of `dbt-core` is colliding with `main` during the Cloud build. Remove it since we declare it explicitly in Cloud when loading all adapters.
=> Remove the PyPI version of core that gets installed as a sidecar for internal PyPI

.github/workflows/pull-request-checks.yml
=> Run on `pull_request_target` to pick up environment variables and secrets on forks

dbt-athena/src/dbt/include/athena/macros/materializations/models/incremental/incremental.sql
This PR solve a issue #688 
The current configuration for iceberg tables uses the same name for all temporary tables, so you cannot run multiple concurrent runs of the same model (airflow backfill)
=> add unique temp table suffix for iceberg tables

dbt-athena-community/pyproject.toml, dbt-athena/pyproject.toml, dbt-athena/src/dbt/adapters/athena/__version__.py
=> bump to 1.9.0final

.github/workflows/_integration-tests.yml
GitHub does not support using environment variables as input defaults.
=> Replace environment variables with string literals in workflow defaults

.github/workflows/pull-request-checks.yml
- update matrix strategies to not fail-fast
- remove the extra changelog entry check that was looking in the old directory
- add DEFAULT_RUNNER as a repo variable (not in this PR, but it contributed to the issue that raised this PR)
=> Fix pull requests workflow
