dbt-labs/dbt-athena

.github/workflows/python-publish.yml, CHANGELOG.md, dbt/adapters/athena/impl.py, dbt/include/athena/macros/materializations/models/incremental/helpers.sql, setup.py
Does what it says on the tin :)
Without this you will receive an error like `Need to add support for column type timestamp`
=> [BUGFIX] Add support for partition fields of type timestamp

dbt/adapters/athena/connections.py, dbt/adapters/athena/impl.py, dbt/adapters/athena/query_headers.py, dbt/adapters/athena/relation.py
👋🏻 Hello everyone !
Since I am very interested in the integration, I am trying to get my hands down this and try to help as much as I can to get all the great features Athena (Engine v3, Iceberg table) or Dbt (`delete+insert` incremental update) provide us.
Since I want to start small in order to introduce myself, I just forked the repo and launching the `flake8` linting returns me some errors. I thought it was a good way to start.
I am also on the #dbt-athena slack channel, please let me know how I can assist you.
=> chore: fix flake8 linting

CHANGELOG.md, README.md, dbt/adapters/athena/connections.py, requirements.txt, setup.py
* https://github.com/dbt-athena/dbt-athena/pull/14
=> Release 1.3.0

.github/workflows/python-publish.yml
This close https://github.com/dbt-athena/dbt-athena/issues/23
=> Trigger publishing to pypi on tag/release

CHANGELOG.md, setup.py
Add release with minimal changelog, for now I added, not sure if we will keep it as we are starting to use release notes.
=> Release v1.3.1

dbt/adapters/athena/__version__.py
=> release: Release 1.3.3

dbt/include/athena/profile_template.yml, dbt/include/athena/sample_profiles.yml
Add more fields when initialising a dbt project with `dbt init`
=> fix: Add more information to default profile

.github/semantic.yml, README.md
Install Semantic PRs from https://github.com/Ezard/semantic-prs
This will require at least two commits.
=> chore: integrate Semantic PRs

requirements.txt
Bump PyAthena, should fix also https://github.com/dbt-athena/dbt-athena/issues/97
=> chore: bump pyathena

README.md
* Add a quick note on avoiding the conflict with `dbt-athena-adapter`.
* Fixes https://github.com/dbt-athena/dbt-athena/issues/103
Signed-off-by: mrshu <mrshu@cisco.com>
=> docs: Avoiding conflict with dbt-athena-adapter

dbt/adapters/athena/__version__.py
=> chore: release 1.3.4

dbt/adapters/athena/query_headers.py
This should fix https://github.com/dbt-athena/dbt-athena/issues/108
Not test yet
=> fix: fix issues on drop statements in the hooks

dbt/adapters/athena/__version__.py
=> chore: bump release version

.pre-commit-config.yaml, dbt/adapters/athena/connections.py, tests/unit/test_adapter.py, tests/unit/test_formatter.py, tests/unit/test_query_headers.py
Bump libs for pre-commit that were breaking the CI, and fix related files that didn't match formatting....
=> fix:bump libs for pre-commit 

dev-requirements.txt
Fix CI due to missing pyparsing
=> fix: add pyparsing to fix ci

dbt/adapters/athena/__version__.py
=> chore: release 1.4.1

dbt/adapters/athena/impl.py
Fix typo in swap_table function in impl.py
=> fix: fix typo in swap_table func log

dbt/adapters/athena/__version__.py
=> chore: release 1.4.2

README.md
Add a section for Credits to mentioned Maintainers and Contributors.
=> chore: add credits section

dbt/include/athena/macros/adapters/relation.sql
Fixes #220 
Fix was originally implemented by @BrechtDeVlieger
=> fix: broken drop view query

dbt/adapters/athena/__version__.py
=> chore: release 1.4.3

dbt/include/athena/macros/materializations/seeds/helpers.sql
=> fix: add `__dbt_tmp` suffix to seed s3 artifacts

dbt/adapters/athena/connections.py, dbt/adapters/athena/session.py
=> feat: allow aws credentials in profiles file

dbt/adapters/athena/__version__.py
=> chore: release 1.4.4

dbt/include/athena/macros/materializations/models/table/create_table_as.sql, dbt/include/athena/macros/materializations/models/table/table_hive_ha.sql
=> fix: wrong condition on s3_naming

.github/workflows/functional-tests.yml
Add possibility to trigger functional test via label.
=> chore: make functional testing triggerable via label

dbt/adapters/athena/__version__.py, setup.py
=> chore: release 1.5.0

README.md
=> docs: fix typo of example config

.github/CODEOWNERS
Add [svdimchenko](https://github.com/svdimchenko) as code owner
=> chore: add svdimchenko as code owner

.pre-commit-config.yaml, README.md, dbt/adapters/athena/column.py, dbt/adapters/athena/connections.py, dbt/adapters/athena/impl.py, dbt/adapters/athena/lakeformation.py, dbt/adapters/athena/relation.py, dbt/adapters/athena/utils.py, setup.py
This PR enables `mypy` typing checks for pre-commit.
=> feat: enable mypy pre-commit check

dbt/adapters/athena/__version__.py
=> chore: release 1.5.1

dev-requirements.txt
=> chore: bump flake after dropping python 3.7 support

dbt/adapters/athena/__version__.py
=> chore: Bump version for release

dbt/adapters/athena/connections.py, tests/unit/test_adapter.py
=> fix: wrong num_retries counting the first run

.github/workflows/ci.yml, CONTRIBUTING.md, README.md, setup.py
Also a small fix in the README badges redirecting to `dlt` package and not `dbt-athena-community`.
Fixes #444
=> chore: add python 3.12 support

.github/FUNDING.yml
Add founding to show sponsor button.
=> chore: add founding for github sponsorship

dbt/adapters/athena/impl.py, dbt/adapters/athena/utils.py, tests/unit/test_utils.py
=> fix: persist_docs too long comment

tests/conftest.py
Sometimes functional tests seems to fail for weird reasons, try to add a retry.
=> fix: add retries to functional tests

dbt/adapters/athena/column.py, dbt/adapters/athena/impl.py
Fix issue when text is used in contraxts
=> fix: use string when text is passed

tests/functional/adapter/test_constraints.py
=> chore: improve tests for contracts

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/other.md
Add issue templates, resolves https://github.com/dbt-athena/dbt-athena/issues/497
=> feat: add issue templates

dbt/adapters/athena/__version__.py
=> chore: prepare release

dbt/adapters/athena/impl.py
Solves https://github.com/dbt-athena/dbt-athena/issues/595
=> chore: cache workgroup

README.md
* remove wrong statement in ha know issues
* remove totally note for athena__end_of_time, because it refer to athena engine version v2, that is now discountinued.
=> fix: improve docs

dev-requirements.txt
=> chore: bump to rc1

dbt/adapters/athena/__version__.py
=> chore: prepare release for 1.8.0rc1

dbt/adapters/athena/__version__.py
Bumped version to 1.8.2 for release
=> chore: Bumped version to 1.8.2 for release

README.md, tests/functional/adapter/test_retries_iceberg.py
Functional tests with iceberg retries fail randomly, this PR setup the amount of num_iceberg_retries to the same amount of parallelism.
Also, if fix a minor mistake in the README.
=> chore: improve function tests for iceberg retries

tests/functional/adapter/test_retries_iceberg.py
Make iceberg retries the double of the parallelism to be sure that we catch edge cases.
=> chore: increase num_iceberg retries

dbt/adapters/athena/__version__.py
=> chore: prepare release 1.8.3

dbt/adapters/athena/__version__.py
=> chore: release 1.8.4

.github/workflows/functional-tests-workflow.yml, .github/workflows/functional-tests.yml, .gitignore, README.md, dbt/adapters/athena/__version__.py
* Leverage repo variables for testing athena
* Align workflow concurrency with other adapters 
* Add dbt Labs banner to Readme
* Make integration test workflows dispatch-able
=> Configure CI testing workflows

dbt/adapters/__init__.py
=> Remove Extra Init file

.github/FUNDING.yml
Remove sponsorship, as the repo is being moved to dbt-labs.
=> chore: remove sponsorship links

dbt-athena-community/pyproject.toml, dbt-athena/src/dbt/adapters/athena/__version__.py
=> Bump to `1.9.0b1`

dbt-athena-community/pyproject.toml, dbt-athena/src/dbt/adapters/athena/__version__.py
=> bump to 1.9.0rc1
